### ISSUE TITLE
Add wireframe display option

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#101]
Add code to display wireframe.
The option has already been added to the Settings pop out menu.

![image](https://user-images.githubusercontent.com/13057505/81002538-6221dd80-8e17-11ea-9e1f-4fed291cbf8f.png)

Use the code that's already existing in CesiumJS sandcastle example to display wireframe.
![image](https://user-images.githubusercontent.com/13057505/80999038-fb4df580-8e11-11ea-9752-75aeb7f298c1.png)

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
done on gw3. please check

**Comment by 3DGISKing** [comment]
sorry. production site also updated. let me know your feedback

**Comment by outsider787** [comment]
Works great!
Thank you.
