### ISSUE TITLE
FPV Mode on mobile

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#106]
Double-tapping on the screen should enter FPV mode at the location that was tapped (similar to double-clicking on desktop starts FPV mode)

When FPV mode is entered from double tapping (or double clicking on screen), display the following 4 extra buttons:
- MOVE LEFT (function: move Cesium camera sideways to left, equivalent to key press "A" on desktop)
- MOVE RIGHT (function: move Cesium camera sideways to right, equivalent to key press "D" on desktop)
- MOVE FRONT (function: move Cesium camera sideways to forward, equivalent to key press "W" on desktop)
- MOVE BACK (function: move Cesium camera sideways to backward, equivalent to key press "S" on desktop)

![image](https://user-images.githubusercontent.com/13057505/81500478-7abf4700-92a0-11ea-8632-2ee825c54371.png)

**Comment by 3DGISKing** [comment]
I see. I should again borrow the phone.

**Comment by outsider787** [comment]
For this issue you don't need to borrow the phone.  
This issue only makes the desktop FPV mode available on mobile devices. It does NOT use the movement tracking of the phone.

You will need the borrowed phone to get this issue working again:
https://github.com/outsider787/construkted_XR/issues/2

**Comment by 3DGISKing** [comment]
Ok

**Comment by 3DGISKing** [comment]
done. please check.

**Comment by outsider787** [comment]
It
