### ISSUE TITLE
zip file on WP server not being deleted

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#108]
Stefan made a change to the WP code to store all the uploaded zip files in the folder `wp-content/uploads/assets/`
This way all the large zip files are kept in the same directory.

However the code that deletes the zip files on WP server is not deleting them from that location.
Can you please adjust the php code to delete the files from that folder location?

**Comment by 3DGISKing** [comment]
I see.

**Comment by outsider787** [comment]
This was an issue only on production server because a page was not created in WP.

![image](https://user-images.githubusercontent.com/13057505/81564761-3f874b80-9366-11ea-9410-d387c95dfea6.png)

**Comment by outsider787** [comment]
This is messy, but works, so will leave it alone for now.

I will think about how to remove dependency of the WP page.
