### ISSUE TITLE
Navigation Help window

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#109]
IGNORE PREVIOUS HELP WINDOW TICKET

**I am thinking about making the focus of the website be the "First Person" exploration ability.**
With that in mind, I want to push instructions to the user on how to use the First Person View mode.

Each time the user views an asset, this help window should be displayed.
The user can use the checkbox at the bottom of the window to not display the info again.

This window should be displayed on desktop displays.
On mobile devices, only display the "Touch" portion of the window.

The HELP window would also be displayed when the question mark symbol "?" on the right tool bar is pressed.

Let me know your thoughts.

![image](https://user-images.githubusercontent.com/13057505/81481685-cd94f200-91ff-11ea-82ca-91c3f9e75455.png)

**Comment by stefanciorici** [comment]
A good idea from a UX perspective I think. Do you want me to work on the design of this overlay? Is is available on the website or is this just a mockup?
