### ISSUE TITLE
tile-server/construkted_api operational check

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#11]
Before access is granted to the front end upload page, check to see if the tile server/construkted_api is functional.
If tile server is not running, out of memory or not responsive, then redirect the user to a different page.

Redirect page:
https://gw3.construkted.com/problem/

**Comment by 3DGISKing** [comment]
This logic had already appended.

**Comment by 3DGISKing** [comment]
Please check.

https://github.com/outsider787/gw3_construkted/blob/db499b1019c22f61940e32f33996d486cef09e9f/wp-content/themes/gowatch-child/includes/frontend-submission/assets/js/upload.js#L105-L124
