### ISSUE TITLE
add resoluitionScaling variable to Cesium

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#111]
Add `resoluitionScaling` to the code.
Set the variable to 1.0

Test with small values of 0.1 or 0.2

**Sandcastle Example to copy**
https://sandcastle.cesium.com/?src=Resolution%20Scaling.html

**Comment by 3DGISKing** [comment]
Please check the working log.

**Comment by outsider787** [comment]
Where in the code did you add it?
I don't see a github commit, and the log doesn't show code changes.

**Comment by 3DGISKing** [comment]
yet not commited.

**Comment by 3DGISKing** [comment]
please see the working doc.
