### ISSUE TITLE
"LOOK" control in FPV mode

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#113]
In FPV mode, I would like to modify the behavior of the Click+drag look.
Right now on Constgrukted FPV mode, when the user clicks and drags the mouse, the view continues to move in the direction dragged.

I would like to change that so that the view only moves as much as the mouse was moved.

I would like the FPV view to behave like this:
https://matterport.com/industries/gallery/basement-workshop

**Comment by 3DGISKing** [comment]
done. please check.
