### ISSUE TITLE
FPV movement speed

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#114]
The popput menu > Settings has a slider which should adjust the FPV movement speed.
That slides should adjust the variable `DEFAULT_HUMAN_WALKING_SPEED `. 
The range of values for the slider should be 0.1 to 1.0

Please implement this change.

![image](https://user-images.githubusercontent.com/13057505/81938294-b91b7580-95c2-11ea-8679-5a2456b363b9.png)

![image](https://user-images.githubusercontent.com/13057505/81938439-e9631400-95c2-11ea-96f9-339496e4563f.png)

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
done. please check.
