### ISSUE TITLE
Multiple API settings bug

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#121]
Weird behavior in the **API URL Settings** tab

- Click **ADD URL** button to add new text input line
- Move the text from the middle line to the bottom line
- Enter new serve in middle line
- Click **Save Changes**
- Middle line disappears. 

(SEE VIDEO)

![Bug002](https://user-images.githubusercontent.com/13057505/85132583-0fee1d80-b207-11ea-9f30-6a8985cb4633.gif)

**Comment by 3DGISKing** [comment]
I see. Let me fix.

**Comment by 3DGISKing** [comment]
Please check.
