### ISSUE TITLE
uploading of garbage data

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#14]
What happens if the user uploads a zip file which is not a 3d model.
Will Cesium Ion send back an error message? 
Can we capture that error and give an indication back to the user that the asset cannot be processed?

**Comment by 3DGISKing** [comment]
What do you mean when you say a zip file which is not a 3d model.
Do you mean Point Cloud?

**Comment by outsider787** [comment]
Maybe the user uploaded a different format that isn't accepted to Cesium Ion, or accidentally sent a zip file of some other file.

**Comment by 3DGISKing** [comment]
I understand.
At now if a user uploads a invalid zip file, WordPress post is created but asset preparation will fail.
Apparently this is an undesirable feature.
So we need to check if the uploaded file is supported file type before we proceed to the asset pipeline.
When I am going to upload an unsupported zip file to Cesium ion, it shows the error message: “Selected files are not supported.”
I noticed that this message appears even if the file is entirely not uploaded.
It appears as soon as I try to upload the file.
But in the current implementation of construkted_api we can not detect error only until the file is uploaded and tiling is started.
So if a user tries to upload invalid zip file, WordPress a post will be created but asset preparation will be suspended.

How to fix this problem?
option1: using Cesium Ion API
If during the tiling any error is detected by Cesium API, construkted_api sends this information to WordPress and then WordPress deletes the post and shows an error message.
But in this case the user should wait until the entire file is uploaded and tiling starts.

option2: detecting file type in WordPress 
Before creating WordPress posts we will detect file type.
If the zip file is invalid, we will show an error message and the subsequent process will be stopped.
I prefer the second idea.

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/76135238-0679e480-6060-11ea-98db-3ccaeed5d7b9.png)

**Comment by outsider787** [comment]
Hmmmm.
I think option 1 is the better idea. 
I like to Let Cesium Ion tell you if it can't process the file. 

There are other reasons why Cesium Ion processing may fail.
- The contents of the zip file are correct, but maybe missing a texture file
- or some of the files are corrupt in some way.
These kinds of error will not be detected until Cesium Ion processing, which means we have to catch errors from Cesium Ion anyway. 

I think we should go with option 1.
I don't care so much if the user has to wait for the file to upload before getting the error.

**Comment by outsider787** [comment]
What is your plan for handling the situation when Cesium Ion returns an error?

**Comment by 3DGISKing** [comment]
Ok. I understand.
I will go option1.
If any error is detected after a zip file is uploaded,  the processing task will fail and construkted_api will send this information to WordPress.
Then WordPress will show an error message in profile page and the corresponding WordPress post will be deleted.

**Comment by outsider787** [comment]
Issue continued #24
