### ISSUE TITLE
Geo Location Addition: transparency adjust

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#17]
Add a slider to adjust the opacity/transparency of 3d tile.
Slider range should be 0.1 to 1.0

**Comment by 3DGISKing** [comment]
done, please check.

**Comment by outsider787** [comment]
There is transparency slider
![image](https://user-images.githubusercontent.com/13057505/76627495-80531780-6511-11ea-89cc-272645fdab58.png)
