### ISSUE TITLE
asset password not updated when editing existing asset

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#2]
When an existing asset is being edited through the Frontend Submission form, and password is selected, the new password is not updated in the asset.
![image](https://user-images.githubusercontent.com/13057505/74357108-677a0980-4d8d-11ea-9f4e-eb410abc3f9b.png)

**Comment by 3DGISKing** [comment]
fixed.

**Comment by 3DGISKing** [comment]
working time: 30 min
