### ISSUE TITLE
User Permission Settings

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#20]
The three buttons should only be available to the owner of the asset.

All other users should not see those buttons.

![image](https://user-images.githubusercontent.com/13057505/76663938-2118f580-6559-11ea-81a6-76ab667b5c1a.png)

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by outsider787** [comment]
The SETTINGS popup menu should be visible to all users. (Right now, the SETTINGS popup menu is not visible for users that are not logged in)

The asset owner should see the extra 3 buttons.

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by outsider787** [comment]
works
