### ISSUE TITLE
Geo-Location popup menu issue

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#23]
The EDIT and SAVE buttons don't work

![image](https://user-images.githubusercontent.com/13057505/76707429-96093e00-66c5-11ea-990a-8eb8125087b4.png)

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by 3DGISKing** [comment]
Did you check?

**Comment by outsider787** [comment]
Yes, Works now
