### ISSUE TITLE
upload garbage data -behavior change

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#24]
Change the way garbage data is handled.
Currently the post and assets get deleted when Cesium Ion throws an error.

The problem with the current behavior is that the error message that get sent to the user is only displayed for a few seconds, then disappears. If the user isn't watching the screen for those few seconds, they don't know there was an error, and all they experience is their post disappearing without an explanation.

And since the post and assets are deleted, we can't investigate out what the problem was.

We should change that behavior. 
When data is uploaded and Cesium Ion (or model-tiler) gives an error, the PROCESSING STATUS should just change to "ERROR Please contact support@construkted.com".
Don't delete anything. We need all the files so we can find out why the error happened, and learn to adjust our system,

![image](https://user-images.githubusercontent.com/13057505/76858703-5ca01200-682e-11ea-8c87-7f629559e8e0.png)

**Comment by 3DGISKing** [comment]
Ok. I agree with your idea.

**Comment by 3DGISKing** [comment]
fixed. please check.
![image](https://user-images.githubusercontent.com/26606704/76884140-2b6c2400-68b8-11ea-9432-2d76ab5d1474.png)

**Comment by 3DGISKing** [comment]
did you check?

**Comment by outsider787** [comment]
Works.
