### ISSUE TITLE
Processing stuck at 70%

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#25]
I've had the issue where the asset processing get stuck at 70%

This is the downloading step. 
The download script encounters files which fail to download. Re-trying the download doesn't work.
I remember this being an occasional issue when we initially wrote the script and when I manually downloaded tiles from Cesium Ion.

I had made some changes to the scrip and renamed it **asset_downloader-v0.8.3.py**.
I tested it many months ago and it didn't fail when I used it.

Consider using  **asset_downloader-v0.8.3.py** as the downloader.

![image](https://user-images.githubusercontent.com/13057505/76862989-42b5fd80-6835-11ea-9f18-2cefe804bee6.png)

**Comment by 3DGISKing** [comment]
This is not the problem related with downloader.
Task looks paused at CPU_INTENSIVE_QUEUE state.

**Comment by outsider787** [comment]
You are still working on this issue?
I had another asset get stuck at 70%

**Comment by 3DGISKing** [comment]
Yes

**Comment by 3DGISKing** [comment]
Let me fix it today.

**Comment by 3DGISKing** [comment]
Fixed. Please check.

**Comment by outsider787** [comment]
Seems to be working.
