### ISSUE TITLE
New user role

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#26]
The default new user role set up in wordpress settings is **Author**.
![image](https://user-images.githubusercontent.com/13057505/76873477-2f5e5e80-6844-11ea-838a-30a4f26078d0.png)
However when a new user registers, their role is always **Contributor**.

Can you find out what the problem is?

**Comment by stefanciorici** [comment]
Fixed, needs to be changed from the theme registration form settings.
