### ISSUE TITLE
Add Terrain to asset display

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#27]
For all assets, display Cesium World Terrain.

- Asset check box should hide/show asset
- Terrain data and Map data should display either Cesium World Terrain or Map data.

Cesium World Terrain is the default 

This selection is NOT PERSISTENT. No data needs to be saved to server.

![image](https://user-images.githubusercontent.com/13057505/76981229-ab25dd00-6910-11ea-9d0e-6662d29d7421.png)

**Comment by 3DGISKing** [comment]
requirement is not clear.
