### ISSUE TITLE
Blog display

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#28]
Why is the test BLOG and "of the website" so squished together and so close to the header? 
Can you please space out that text?

Also, where is the test "of the website" edited? I would like to change it.

![image](https://user-images.githubusercontent.com/13057505/76982980-0a84ec80-6913-11ea-9372-7103eb208b4a.png)

**Comment by outsider787** [comment]
Same for when viewing a blog article. The top text (HOWTO and LAST ADDED ASSETS) looks too close to the header.

![image](https://user-images.githubusercontent.com/13057505/76997103-154a7c00-6929-11ea-86c0-dac80805d5b7.png)

**Comment by stefanciorici** [comment]
@outsider787 - This happened because the header did not have any spacing below. I added a 30px spacing for the header which should be already ready so see on the website, went throught he links from the footer to verify which of them needed a back fixing as they had the title block with a white space where I added a negative margin to get it to look like it was. 

Regarding the blog title I see you already managed to remove it completely. Do we need it or to leave it without?

**Comment by outsider787** [comment]
The 30px you added have changed the way the 3d models look.
Now there's a thick white bar at the top.

![image](https://user-images.githubusercontent.com/13057505/77059835-f9d58480-69ad-11ea-8c64-caa16d60e330.png)

**Comment by stefanciorici** [comment]
Please make sure you do a hard refresh (CMD+R or CTRL+R) or clear you cache.

**Comment by outsider787** [comment]
That worked.
As for the Blog title disappearing, I had selected "Blog" from the Settings > Reading >Post Page dropdown. 
Previously nothing was selected for blog in that location.

That's why the BLOG title disappeared.
Is there a different way to control which page gets loaded for the blog?

![image](https://user-images.githubusercontent.com/13057505/77060850-a106eb80-69af-11ea-8bc7-68ebeac91628.png)

**Comment by stefanciorici** [comment]
Yes, the blog page can be created with the drag and drop builder to be able to change the layout more. Having the page set there uses only the options from the Theme Settings where you can change the post view (grid, list, etc) and the sidebar settings

**Comment by outsider787** [comment]
Is there another way to set the blog page from the theme?
If I set the posts page to --SELECT--, what page is the theme using to display the blog?

![image](https://user-images.githubusercontent.com/13057505/77163138-d7ae3600-6a83-11ea-9df1-9f304bce42f2.png)

**Comment by stefanciorici** [comment]
@outsider787 - You might create a blog page with the drag and drop builder instead, without setting it anywhere as a "blog". You can use any post view, pagination, number of posts and layouts there.

**Comment by stefanciorici** [comment]
@outsider787 - Do we need a special layout for the blog page?
