### ISSUE TITLE
Geo-Location number precision

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#29]
Change the number of digits **after** the decimal point:

Latitude/ Longitude : 8 digits
Altitude: 3 digits
Heading : 3 digits

![image](https://user-images.githubusercontent.com/13057505/76984333-12459080-6915-11ea-9381-8594daa6f83c.png)

**Comment by stefanciorici** [comment]
Done, I changed it, works after the update.

**Comment by outsider787** [comment]
Thank you
