### ISSUE TITLE
Geo-location Position tool

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#30]
Can we shrink the size of the position/rotation tool?
It's too big, especially the rotation tool. 
If I'm zoomed into the object, sometimes I can't even see the rotation tool since it's too large.

![image](https://user-images.githubusercontent.com/13057505/76984644-7e27f900-6915-11ea-8d18-291fc0854fe3.png)

![image](https://user-images.githubusercontent.com/13057505/76984689-913ac900-6915-11ea-849a-c6a5ec9a7dd1.png)

**Comment by outsider787** [comment]
On Cesium Ion website, the position/rotation tool remains the same size regardless of asset zoom

![image](https://user-images.githubusercontent.com/13057505/76985258-55ecca00-6916-11ea-9b45-33c768e63903.png)

![image](https://user-images.githubusercontent.com/13057505/76985299-6604a980-6916-11ea-9b8b-62b482f4562c.png)

**Comment by 3DGISKing** [comment]
Ok. Let me try.

**Comment by 3DGISKing** [comment]
please check.

**Comment by outsider787** [comment]
Yes, works much better now.
Thank you!
