### ISSUE TITLE
File upload speed display

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#32]
What units are actually being diplayed? Megabits per second or Megabytes per second?

Second, can we add one decimal place to the "Uploading Speed" number

![image](https://user-images.githubusercontent.com/13057505/77061068-0b1f9080-69b0-11ea-8f48-064eeb5500d2.png)

**Comment by stefanciorici** [comment]
It is Megabytes per second. I also added one decimal to be shown as well.

**Comment by outsider787** [comment]
I don't see the change. 
Did you update git and website? Or just git?

**Comment by stefanciorici** [comment]
I did add the code to the website, updated git now.

**Comment by outsider787** [comment]
Thank you
