### ISSUE TITLE
New Go-Watch theme

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#33]
What are the changes in the new main go-watch theme that you uploaded to the site?

**Comment by stefanciorici** [comment]
Updated /includes/frontend-submission/tszf-functions.php and made sure we verify if the functions exists for "tszf_allowed_extensions" before creating the function definition so it became like this:

if(!function_exists('tszf_allowed_extensions')) {
    function tszf_allowed_extensions()
    {
        $extesions = array(
            'images' => array('ext' => 'jpg,jpeg,gif,png', 'label' => __('Images', 'gowatch')),
            'video'  => array('ext' => 'mp4,mpeg,mpeg4', 'label' => __('Videos', 'gowatch')),
        );

        return apply_filters('tszf_allowed_extensions', $extesions);
    }
}

**Comment by outsider787** [comment]
Thank you
