### ISSUE TITLE
Point Cloud file giving error

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#34]
I uploaded a new LAZ (laser point cloud) and I got an error message right away.
There was no processing that was done. The error message appeared right away.

https://gw3.construkted.com/?post_type=video&p=1810
![image](https://user-images.githubusercontent.com/13057505/77061540-c811ed00-69b0-11ea-8806-0f8c91e397ad.png)

Test with sample LAZ file
https://uploads-construkted.s3.us-east-2.amazonaws.com/test_assets/Ancient+Corinth_SPATIAL_SUBSAMPLED_02.laz

**Comment by 3DGISKing** [comment]
This is not a specific problem for laz file.
obj file also fails.
The reason is because the 'upload_data_type' become empty.
