### ISSUE TITLE
Server optimization

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#35]
Web server is often at or near 100% utilization when a page is requested.
Implement optimizations to reduce resource usage of web server.

![image](https://user-images.githubusercontent.com/13057505/77070855-63ab5980-69c1-11ea-8c2d-1838d180ecef.png)

**Comment by outsider787** [comment]
The PageSpeed Insights from google is showing a very low result.
https://developers.google.com/speed/pagespeed/insights/?url=gw3.construkted.com&tab=desktop
![image](https://user-images.githubusercontent.com/13057505/77071716-e680e400-69c2-11ea-9ee5-52f96edbc10b.png)

**Comment by stefanciorici** [comment]
I did some customizations, downloaded and optimized the images used, compressed files and minified some stuff, we do have an improvement over this:  https://prnt.sc/rj34z1

**Comment by outsider787** [comment]
That's a huge improvement.
Now I have a baseline gong forward to test against.

**Comment by outsider787** [comment]
The performance is once again showing low numbers.
Is this because we disabled MinifiJS? Or adjusted some settings in the WP Cache plugin?

https://developers.google.com/speed/pagespeed/insights/?url=gw3.construkted.com&tab=desktop

![image](https://user-images.githubusercontent.com/13057505/77320099-50acc800-6ce6-11ea-99d8-8bc860e6e34a.png)
