### ISSUE TITLE
Geo-location save

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#36]
If I type a latitude and longitude, and then click the "SAVE" button, the values are not saved/updated.
Next time the asset page is loaded, the old lat/lon values are there.

HOWEVER
If the position tool is opened, and adjustments are made, then the lat/lon IS saved when "SAVE" button is clicked

![image](https://user-images.githubusercontent.com/13057505/77160564-fad5e700-6a7d-11ea-9e2e-bcae0581b98f.png)

**Comment by 3DGISKing** [comment]
Let me check and fix.

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by outsider787** [comment]
Not working.

**Comment by 3DGISKing** [comment]
I have already tested. Let me retest.

**Comment by 3DGISKing** [comment]
Very strange.

**Comment by outsider787** [comment]
Issue seems to still be there.

**Comment by 3DGISKing** [comment]
Data is correctly save to WP db, but wrong data is fetched for asset view page.
I think this may be related to the double post issue.
