### ISSUE TITLE
Asset Metadata

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#37]
The latitude longitude should only display 8 digits after the dot.

**Polygon Model**
If the asset is a polygon model, also display the "Software" used. Since many options can be selected, display all of them, separated by coma (,)
Asset to use for testing polygon model attributes:
https://gw3.construkted.com/asset/3yx6yry34e/
![image](https://user-images.githubusercontent.com/13057505/77163439-776bc400-6a84-11ea-8988-0c46df41acf5.png)

**Point Cloud**
If the asset is a point cloud, then display the text "POINT COUNT" and display the contents of the "point cloud size" field in Front End form.
For software, display the "Point Cloud software" 
Asset to use for point cloud attribute:
https://gw3.construkted.com/asset/jiut8549uw/
![image](https://user-images.githubusercontent.com/13057505/77163667-ee08c180-6a84-11ea-8e95-ad5ae116c1fa.png)

**Comment by stefanciorici** [comment]
@outsider787 Fixed. Added Point count value if non-empty and asset type is Point Cloud. Also the software should be shown normally now.
