### ISSUE TITLE
Wordpress technical issue?

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#38]
I just received this email sent from the wordpress server.
Is this something we should worry about?
----------------
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with your theme, goWatch.

First, visit your website (http://gw3.construkted.com/) and check for any visible issues. Next, visit the page where the error was caught (http://gw3.construkted.com/wp-admin/post.php?post=392&action=edit&message=1) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://gw3.construkted.com/wp-login.php?action=enter_recovery_mode&rm_token=r7drpGpVSy1xSduTXeYst4&rm_key=4NoncBtgpedAxDpfZNeEQP

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3.2
Current theme: Child of goWatch Theme (version 1.0)
Current plugin:  (version )
PHP version 7.3.15

Error Details
=============
An error of type E_ERROR was caused in line 426 of the file /home/gw3/public_html/wp-content/themes/gowatch/includes/theme-setup.php. Error message: Uncaught Error: Cannot use object of type WP_Error as array in /home/gw3/public_html/wp-content/themes/gowatch/includes/theme-setup.php:426
Stack trace:
#0 /home/gw3/public_html/wp-includes/class-wp-hook.php(288): airkit_verify_ls('')
#1 /home/gw3/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#2 /home/gw3/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/gw3/public_html/wp-admin/admin-header.php(281): do_action('admin_notices')
#4 /home/gw3/public_html/wp-admin/edit-form-advanced.php(419): require_once('/home/gw3/publi...')
#5 /home/gw3/public_html/wp-admin/post.php(198): include('/home/gw3/publi...')
#6 {main}
  thrown

**Comment by stefanciorici** [comment]
No need to worry, it's a license verification error. Was actually fixed in an update for the main theme I think.
