### ISSUE TITLE
Asset position and default view

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#39]
Is there any reason why asset position is stored ad x,y,z and default view is stored as lat/long/alt?

![image](https://user-images.githubusercontent.com/13057505/77187407-cf1d2600-6aaa-11ea-8739-dba573467a7a.png)

**Comment by 3DGISKing** [comment]
There is no special reason.

**Comment by 3DGISKing** [comment]
What kind of format do you recommend?
Is there any problem in current format?

**Comment by outsider787** [comment]
Let's store all the position information in lat/long/height format for all assets

**Comment by 3DGISKing** [comment]
Ok.

**Comment by 3DGISKing** [comment]
Done. Please check.
**But all saved "asset_geo-location"  will no longer work.**

**Comment by outsider787** [comment]
I understand that the saved position will no longer work. 
I will update the existing models manually.
