### ISSUE TITLE
The stored 'asset_geo_location_data' is not correctly fetched to the corresponding asset view(construkted.js)

### ISSUE THREAD

**Issue by 3DGISKing** [outsider787/gw3_construkted#40]
The asset (slug: mq31suli3w, post Id 1847) has obviously following data.

{"longitude":"60.00000000","latitude":"50.00000000","height":"70.00000000","heading":"80.00000000","pitch":"0.00000000","roll":"-0.00000000","scale":{"x":1.0000000000000002,"y":1,"z":0.9999999999999998}}

![image](https://user-images.githubusercontent.com/26606704/77217976-8d02eb80-6b61-11ea-9cff-99ecc4b86b2c.png)

But the corresponding asset view(https://gw3.construkted.com/asset/mq31suli3w/) shows wrong(maybe old) 'asset_geo_location' data.
![image](https://user-images.githubusercontent.com/26606704/77218002-c8051f00-6b61-11ea-9954-275b90eab433.png)

Who has any idea for this bug?

**Comment by outsider787** [comment]
The plugin "WP Super Cache" is caching the position data, and not serving the most current.
I just disabled the plugin, and the position data loads.

@stefanciorici do you know any way to not cache this data?

**Comment by stefanciorici** [comment]
@outsider787 I think there is an option in the plugin settings to regenerate cache when a post is updated. Was the data from this asset updated?

**Comment by outsider787** [comment]
Yes, the data from that asset was updated.

**Comment by stefanciorici** [comment]
@outsider787  Activated the plugin now with this option: https://prnt.sc/rk8acw Can you please check it out?

**Comment by 3DGISKing** [comment]
The plugin "WP Super Cache" 's "Clear all cache files when a post or page is published or updated." option works well.
Let 's not forget that this option should always become checked(true).
