### ISSUE TITLE
Custom field values are erased when editing post

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#41]
Clicking UPDATE while in the post edit page, will remove any contents of the following custom fields:
- uploaded_file_size
- asset_geo-location
- default_camera_position_direction
Any ideas why that is happening?

![image](https://user-images.githubusercontent.com/13057505/77225997-f0355380-6b4a-11ea-9e63-f28127941ba5.png)

![image](https://user-images.githubusercontent.com/13057505/77226015-27a40000-6b4b-11ea-82d2-4259dfd021ff.png)

**Comment by stefanciorici** [comment]
Seems the values for these fields are empty: https://prnt.sc/rk7d8u and on save it overwrites them with the data.

**Comment by outsider787** [comment]
But even if you change the value in those fields for a specific post, they do not get saved when the post is updated.

**Comment by stefanciorici** [comment]
@outsider787 I managed to fix it, should work fine now.

**Comment by outsider787** [comment]
What was the problem?
So have an idea where to look if this happens elsewhere.

**Comment by stefanciorici** [comment]
@outsider787  - Just added the commit, should be available here already.
