### ISSUE TITLE
Format JSON data display

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#43]
Format the JSON data in a more readable and compact format for the "Processing State" settings page.
Display the 'NAME' elements in a list, and for each name allow for some way to expand to see more information about it, where the remainder of data is displayed.

https://gw3.construkted.com/wp-admin/options-general.php?page=construkted_page&tab=processing-state

**Comment by stefanciorici** [comment]
Added new toggle for each item to see all the information.

**Comment by outsider787** [comment]
Is this how it's supposed to look?

![image](https://user-images.githubusercontent.com/13057505/77318650-cb281880-6ce3-11ea-979b-af6603c6a677.png)

**Comment by outsider787** [comment]
Looks great!
