### ISSUE TITLE
Upload page check

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#44]
Before allowing user access to upload page, check if tile01.construkted.com API is functioning.

If the API is not up, then do not display the upload page.
Display a page which informs the user there is an error,

**Comment by stefanciorici** [comment]
Done, commit https://github.com/outsider787/gw3_construkted/commit/1583a07c6856f3442492e02d471801eea57e7477

I would like to test it anyway before launch, if possible to stop the API server to see if everything is fine.
