### ISSUE TITLE
'End Measurement' Button

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#45]
The action performed by the "End Measurements" button should also be performed:
- when the  user closes the popup menu (by clicking on the 'X') 
- when the user changes to a different menu.

![image](https://user-images.githubusercontent.com/13057505/77250478-9e5dfd80-6c1e-11ea-84f1-3be817e94e69.png)

**Comment by stefanciorici** [comment]
Done, should be available on the website already.
