### ISSUE TITLE
"Estimate Altitude" button

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#46]
In the Geo-Location popup menu, a new button was added.
When button is pressed, find the terrain altitude at the current LAT/LONG coordinates, and place that altitude value in the "Altitude" field.

If the LAT/LONG coordintates are 0,0 (which means the asset hasn't been placed on the planet) return an error informing the user that Latitude and Longitude coordinates need to be entered before using the Estimate Altitude button.

![image](https://user-images.githubusercontent.com/13057505/77252317-6ad4a080-6c29-11ea-8533-83798a7247de.png)

**Comment by 3DGISKing** [comment]
done. please check.

**Comment by outsider787** [comment]
Checked.
The "Estimate Altitude" button does get a value of the altitude, and it does display it in the Altitude field, but it does not update the position of the model.

The altitude value should be applied to the 3d tile model.

Also, when "Estimate Altitude" button is pressed, only display 3 decimal places for the altitude.

**Comment by 3DGISKing** [comment]
ok

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by outsider787** [comment]
I don't see any change.
Did you commit the changes?
