### ISSUE TITLE
Point Cloud with geo-location

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#47]
This point cloud asset is already geo-referenced. (The original .laz file has lat/long information for each point.)
This is common for point clouds. Often the point cloud is already geo-referenced.

![image](https://user-images.githubusercontent.com/13057505/77256973-e9d8d180-6c47-11ea-923a-5da5fb7c08df.png)
- If the file "tileset.json" for the asset indicated TRUE for "geo-referenced" then use the asset's location. In the geo-location pop-up menu, disable the lat/long fields.

- If the file "tileset.json" for the asset indicated FALSE for "geo-referenced" then use lat/long location that is entered in the geo-location pop-up menu.

**Asset with existing geo-location** for testing
https://gw3.construkted.com/asset/vlfrcz2iry/

**Comment by 3DGISKing** [comment]
done. please check.

**Comment by outsider787** [comment]
I can see you edited the geo-location popup menu to grey out the lat/long fields.
However he model still loads at a weird angle, and not in the right location.
![image](https://user-images.githubusercontent.com/13057505/77307284-5945d400-6ccf-11ea-95c5-6eb1aac62080.png)

This is what the model looks like in Cesium Ion
![image](https://user-images.githubusercontent.com/13057505/77307239-4a5f2180-6ccf-11ea-8947-e149b5a3c8ba.png)

**Comment by 3DGISKing** [comment]
Ok. Let me check

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by outsider787** [comment]
Looks great.
We should still allow the user to adjust altitude settings.
Is it possible to only give the user altitude control on assets which are have geo-location stored in the model?

If you look at this model, it looks like it's under the terrain.
https://gw3.construkted.com/asset/vlfrcz2iry/

Any ideas how to solve this?

**Comment by 3DGISKing** [comment]
Let 's make sure user change altitude textbox in case of georeferenced asset.

**Comment by 3DGISKing** [comment]
please check.

**Comment by outsider787** [comment]
Looks great!
