### ISSUE TITLE
Display issue: assets with no geo-location 

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#48]
Assets that have no geo-location (no lat/long coordinate) do not display properly.
I think it may have something to do with the fact that Cesium World Terrain is being used because this was not an issue before.
The problem is evident when you double-click on a model to enter FPV mode. 

I don't know how to solve this.

**After Double-clicking on the model**
The bottom portion of the model dissapears.
![image](https://user-images.githubusercontent.com/13057505/77262077-b27b1c80-6c69-11ea-8d2e-0b52e5dc5993.png)

**Comment by 3DGISKing** [comment]
done. please check.
