### ISSUE TITLE
Move the EMBED button

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#49]
The EMBED button is burried under a few mouse clicks.
Move the EMBED button to a spot which allows for easier access.

@stefanciorici where do you think it should go?

![image](https://user-images.githubusercontent.com/13057505/77324694-84d7b700-6ced-11ea-80a2-f17d42202813.png)

**Comment by stefanciorici** [comment]
@outsider787 - Done, both mobile and desktop versions.
