### ISSUE TITLE
Display API information (devel01/tile02 servers only)

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#50]
## FOR DEVEL01/TILE02 SERVERS ONLY
At the top of the page (besides the Refresh button) can we display the following information:
- state of API (Up/down)
- name and number of jobs being processed
- name and number of jobs in the tiling processing queue

![image](https://user-images.githubusercontent.com/13057505/77537857-29383580-6e75-11ea-8396-70ad1200597e.png)

**Comment by 3DGISKing** [comment]
ok

**Comment by 3DGISKing** [comment]
done. please check.

**Comment by 3DGISKing** [comment]
Did you check?

**Comment by outsider787** [comment]
Please make the change to the gw3 website as well.

**Comment by 3DGISKing** [comment]
I see.
