### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#51]
Please write complete API documentation for:
- construkted_API that runs on tile01 server (the api that interfaces with Cesium Ion)
- construkted_API that runs on tile02 server (the api which does the tiling locally)

**Comment by 3DGISKing** [comment]
Done. Please see google doc.

**Comment by outsider787** [comment]
Thank you.
Is the API the same for the tiling branch?

**Comment by 3DGISKing** [comment]
Yes
