### ISSUE TITLE
Terrain should hide model

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#53]
When viewing a 3d tile on Cesium Ion, the 3d tile will disappear under the terrain.
(The terrain altitude is 120m) As you can see when the 3d tile altitude (height) moved below 120m, the model gets hidden.

On GW3 website, that is not the same behaviour. The terrain does now hide the model.

I want the behavior of  Cesium Ion (Terrain hiding the model when model is below terrain) to work on GW3 website.

https://drive.google.com/file/d/1wOqF0sHE4PFLSoUCTTSpXAZJvfo7UNoc/

**Comment by 3DGISKing** [comment]
Ok. Let me fix.

**Comment by 3DGISKing** [comment]
done. please check.

**Comment by outsider787** [comment]
Works great!
