### ISSUE TITLE
Modify widget

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#54]
The footer displays the "Website Stats" widget.
Change the text to read "UPLOADED ASSETS" and center the number that is below the text.

![image](https://user-images.githubusercontent.com/13057505/77830903-33229880-7102-11ea-90d5-000c8c25674e.png)

**Comment by stefanciorici** [comment]
@outsider787 - Fixed. The best way to do this is by translating it so the changes are not lost on updates. I added a plugin named Loco Translate which is used for changing words within the theme. This is the best way to do that. I tried to follow the same steps and create translateable strings in the child theme as well where I could. You can change things in the future if you'll need.
