### ISSUE TITLE
Add shading option

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#56]
Some models do not have textures.
CesiumJS has some shaders that apply lighting
https://sandcastle.cesium.com/?src=Physically-Based%20Materials.html

Can you test some of the shading methods to see how models without texture will look?

https://gw3.construkted.com/asset/64su9iqbso/
**Model without texture**
![image](https://user-images.githubusercontent.com/13057505/77850425-6d427780-71a0-11ea-8aa6-0f8435a86e61.png)

**Comment by 3DGISKing** [comment]
I have done some tests with a simple non textured obj file.

When I use the Cesium js Entity API, it looks good.
![image](https://user-images.githubusercontent.com/26606704/77920338-f062eb00-72d0-11ea-9e66-1422b3d6b5d2.png)

But when I use the tileset which is generated from same obj file, I can not feel three-dimensional effect.

![image](https://user-images.githubusercontent.com/26606704/77920520-286a2e00-72d1-11ea-914f-2fd286d80ffb.png)

I need to check more.

**Comment by outsider787** [comment]
The top picture is displayed in your sandcastle code. 
Can you post the link to the sandcastle code?

**Comment by 3DGISKing** [comment]
Can not make sandcastle code because we use custom obj data which does not exist on Cesium server.
May I upload to devel01 or gw?

**Comment by outsider787** [comment]
yes, you can upload to devel01 site

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
https://devel01.construkted.com/SimpleObj/

**Comment by outsider787** [comment]
And if you use the 3d tile model from cesium there is no shading, is that correct?

![image](https://user-images.githubusercontent.com/13057505/77924544-c62e1080-7271-11ea-861b-e426aa18881d.png)

**Comment by 3DGISKing** [comment]
yes.

**Comment by 3DGISKing** [comment]
Normal data is generated only when we use '3D Model Option'. 

Please send original zip file for this asset.
https://gw3.construkted.com/asset/64su9iqbso/

I can not find it in upload bucket.

**Comment by 3DGISKing** [comment]
https://gw3.construkted.com/asset/a5i8b7ykgs/

![Uploading image.png…]()

**Comment by 3DGISKing** [comment]
Please use the following option for untextured 3d model.

![image](https://user-images.githubusercontent.com/26606704/77978482-dc50d500-7334-11ea-9221-ca1e55471cf5.png)

**Comment by outsider787** [comment]
I understand.
I will do some testing as well.

**Comment by 3DGISKing** [comment]
Ok
