### ISSUE TITLE
Visual errors on grid views

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#57]
On the home page, the thumbnail display shows a double " / / ".
This happens on both types of thumbnail grid views.

Can you please adjust/remove so it looks cleaner.

![image](https://user-images.githubusercontent.com/13057505/77850627-ce1e7f80-71a1-11ea-89ae-35d30f8f535a.png)

![image](https://user-images.githubusercontent.com/13057505/77850633-d4acf700-71a1-11ea-8df7-9985fa4ce75e.png)

**Comment by stefanciorici** [comment]
Fixed.
