### ISSUE TITLE
change file access

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#58]
# For tile02 server only
**We will remove the /mnt/s3-assets and /mnt/s3-uploads mount points on tile02 server.**

We will access the Wasabi S3 storage through the **AWS CLI**  and  **AWS SDK for nodeJS** (I already installed)
https://aws.amazon.com/sdk-for-node-js/

Usage with wasabi:
https://wasabi-support.zendesk.com/hc/en-us/articles/115002350192-How-do-I-use-the-AWS-SDK-for-JavaScript-with-Wasabi-

**The AWS CLI and AWS SDK for nodeJS provides a much faster way to transfer files to and from S3 buckets.**

Please modify construkted_API to work with AWS SDK nodeJS

**Comment by 3DGISKing** [comment]
ok

**Comment by outsider787** [comment]
Test on tile02 server.
Once it's working we can merge this change into tile01 server.

**Comment by 3DGISKing** [comment]
We can no longer use the bucket as if it is a local file system on the server.
Before tiling we need to download zip or laz file from the upload bucket.
After tiling and packaging we should upload the asset file to the asset bucket.

But currently, the asset server uses the mounted asset bucket to serve assets.  
I believe you do not remove the mounted asset bucket from the asset server.

**Comment by 3DGISKing** [comment]
Please check and let me your thinking.

**Comment by outsider787** [comment]
I know asset01 server uses the mounted asset bucket. That does not change.

The servers that runs the consrukted-API (tile01 and tile02) should use the AWS SDK to access the uploads and asset buckets for moving files from local storage to Wasabi, and from Wasabi to local storage.

Is that more clear?

**Comment by 3DGISKing** [comment]
clear. that is consistent with my thinking.
I will go.

**Comment by 3DGISKing** [comment]
done. please check.
