### ISSUE TITLE
Asset server alternative

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#59]
Can you explore the option of reading sqlite 3d tile directly from the web browser using this sql.js library?
https://github.com/sql-js/sql.js
Is this possible?

If this is possible, I would like to test and compare against the current setup in terms of performance. 
Is reading 3d tiles faster by using the asset server, or is it faster to read 3d tiles by using sql.js?

**Comment by 3DGISKing** [comment]
Ok. I see.

**Comment by 3DGISKing** [comment]
We can read a sqlite db file from the Web browser using sql.js.
But web browser can read(access) only db file hosted at the same site.

Let me remind Cesium js 's 3D Tileset API.

 var tileset = new Cesium.Cesium3DTileset({
     url : 'http://localhost:8002/tilesets/Seattle/tileset.json'
});

There must be a server to handle request and send the tileset.json.

Do you want to display(make) 3DTileset (instance) in browser without any server?

**Comment by outsider787** [comment]
> Do you want to display(make) 3DTileset (instance) in browser without any server?

Yes.
I'm trying to think of ways to speed up the delivery of 3d tiles to the browser.

**Current delivery path**
Wasabi (3d tile storage) -->  Amazon EC2 server (asset server)  -->  Web browser

If we could cut out the Amazon EC2 (asset server) that would improve performance.

Do you have any ideas?

**Comment by 3DGISKing** [comment]
"Yes." I can not understand this answer.

**Comment by outsider787** [comment]
Yes, I would like to display 3DTileset in browser without any server.

I would like to test the performance difference.

**Comment by 3DGISKing** [comment]
I still can not understand your idea. 
Without any server, how can I handle the request which the browser send for tileset.json and the tile content?
