### ISSUE TITLE
upload file extension error message

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#6]
When a file other then ZIP file is uploaded, the site generates a generic error.
Please change the error to read "Only ZIP file extensions are acceptable for upload"

**Comment by outsider787** [comment]
![image](https://user-images.githubusercontent.com/13057505/75267609-79639f80-57c4-11ea-9c59-de1ceec5575b.png)

**Comment by 3DGISKing** [comment]
fixed
