### ISSUE TITLE
Variable should be obtained from WordPress

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#61]
The variable 'CONSTRUKTED_CESIUM_ACCESS_TOKEN' defined in gowatch-child/functions.php  should be be obtained from a field in the Settings -> Construkted settings page  https://gw3.construkted.com/wp-admin/options-general.php?page=construkted_page 
Create another tab called "Cesium Settings" and add a field which will store the value for CONSTRUKTED_CESIUM_ACCESS_TOKEN.

Adjust the code to use the value from the Cesium Settings field.

![image](https://user-images.githubusercontent.com/13057505/77972414-4fb7ff80-72bf-11ea-967a-c2fa03000571.png)

**Comment by stefanciorici** [comment]
Done.
