### ISSUE TITLE
API check

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#62]
Can you check something
I think there's another API check done once a file has been selected. 
I've had a behaviour where I select a file, but the progress indicator never appeared. This was at a time when the api was under heavy load.
![image](https://user-images.githubusercontent.com/13057505/78019260-5d03d700-731d-11ea-8eda-696368df8096.png)

Can you check if there's another check at that point?
If there is, remove it. We are already doing an API check on page loading.

**Comment by stefanciorici** [comment]
@outsider787 - Do you think we need another one? It duplicates in a way the one on the page load.

**Comment by outsider787** [comment]
Ww do not need another one. 

If there is another check, we should remove it.

**Comment by stefanciorici** [comment]
I was saying  that we are doing a verification on page load, not sure we should do another one when the button is clicked.

**Comment by outsider787** [comment]
There's some more testing I need to do before closing.
