### ISSUE TITLE
disable/remove Playlists and Favorites

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#63]
Disable/Remove the Favorites and Playlists code from the profile page, and user menu.

**Profile Page**

![image](https://user-images.githubusercontent.com/13057505/78019680-19f63380-731e-11ea-8caf-67a4a526f705.png)

**user menu** 

![image](https://user-images.githubusercontent.com/13057505/78019745-2bd7d680-731e-11ea-98ed-65cc2ff2f7da.png)

**Comment by stefanciorici** [comment]
Done.
