### ISSUE TITLE
Image for assets

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#64]
After a new asset is uploaded, the thumbnail has three (3) states.
When the asset is initially uploaded, the thumbnail image "ASSET IS BEING PROCESSED" is assigned to asset. Once processing is complete, a new thumbnail is displayed "NO THUMBNAIL IMAGE HAS BEEN SET". Once a thumbnail has been set by the  user, then that thumbnail will be displayed.

The first two thumbnails are only temporary until the user generated a proper thumbnail of the asset.
The problem is that the media library becomes full of these temporary images.

Is there anything we can do to restrict thumbnail creation for those 2 temporary images?

![image](https://user-images.githubusercontent.com/13057505/78020983-63478280-7320-11ea-8a08-c0ab00b726db.png)

**Comment by stefanciorici** [comment]
@outsider787  - Done. From what I tested it seems to be working fine, done 3-4 tests already. Can you please another check on your end to see if everything runs as it should?

**Comment by outsider787** [comment]
I'll do some tests as well.

**Comment by outsider787** [comment]
seems to work.
