### ISSUE TITLE
change button on purchase page

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#70]
Can we change the "SIGN UP NOW" button to something more like the other buttons on the website? Maybe also change the text to read "PURCHASE NOW" ?

It took me quite a while to realize that it was a button, since it looked like regular text (with a very subtle border) 

Maybe make the button have a blue background (like every other button on the woocommerce pages)?

![image](https://user-images.githubusercontent.com/13057505/78283780-5081a900-74ec-11ea-81c4-f7e7f508b29c.png)

**Comment by stefanciorici** [comment]
These can be changed from the Subscription plugin options I think from here, I just did: https://gw3.construkted.com/wp-admin/admin.php?page=wc-settings&tab=subscriptions

**Comment by outsider787** [comment]
Is it possible to move the button to the left side of the screen, and change the background color to blue with white text like most other buttons on the website?
And make it BIGGER!

To me that PURCHASE button is hard to see. 
I don't think that the purchase button should be hard to see and hard to find. It should be the EASIEST button to find, as I don't want the user experience to suffer just one step before they send me their money :)

![image](https://user-images.githubusercontent.com/13057505/78429429-93559500-7642-11ea-8d3c-fff775af611d.png)
