### ISSUE TITLE
avatar and profile image chage

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#72]
I am not able to change eiotehr avatar or profile picture.
The system allows me to upload a file, but nothing gets updated once I click on the "Update Profile" button.

![image](https://user-images.githubusercontent.com/13057505/78357845-2a0d4d80-7580-11ea-9710-f79f7c2635b6.png)

**Comment by stefanciorici** [comment]
I believe this was fixed in the original theme update. Let's try to update that to the latest version and see if it works normally.

**Comment by outsider787** [comment]
I updated the theme to the latest version.
However there's still a bug:
- When I change the avatar image, the profile image is lost. 
- When I change the profile picture, the avatar image is lost.

**Comment by stefanciorici** [comment]
It was not the latest version of the original theme, I updated it now, seems to be working.

**Comment by outsider787** [comment]
It doesn't work for me.
I have the same issue. Once I set one image, the other disapears.
