### ISSUE TITLE
User disk quota check required

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#74]
Need to put in place a way to check if the user's storage is equal to or larger then their quota.

If the Used Storage is equal to or larger then the Disk Quota, don't show the user the upload page.
Show them a different page that informs them of the error, and provide a link to the pricing page.

![image](https://user-images.githubusercontent.com/13057505/78425841-81272700-7641-11ea-8096-3bb2314e8ab1.png)

**Comment by stefanciorici** [comment]
Done.

**Comment by outsider787** [comment]
Doesn't work for me.

I have the free plan (2GB) and I'm using 6GB of storage.
This should mean I would not be allowed to upload anymore, but I can still access the upload page.

**Comment by outsider787** [comment]
works now
