### ISSUE TITLE
Thumbnail clickable area

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#78]
There is a weird discrepancy in the clickable area for a thumbnail. 

The red area is clickable. Below that area, only the text is clickable. 
The space below the red area feels weird since it's not consitent.

Either make the entire thumbnail area clickable, or make just the text clickable.
What do you think Stefan?

![image](https://user-images.githubusercontent.com/13057505/78700396-476d4f00-78d3-11ea-8fa9-e0b1d22d270e.png)

**Comment by stefanciorici** [comment]
Please try to update from git.

**Comment by outsider787** [comment]
Updated from git.
There's a faint line that appears when hovering on the thumbnail

![image](https://user-images.githubusercontent.com/13057505/78831102-1403f080-79b7-11ea-9c5c-accf70eca4c1.png)

**Comment by stefanciorici** [comment]
Was fixed earlier in a commit.

**Comment by outsider787** [comment]
The obvious line is gone, but there's a still a subtle blue line that appears on the right side of the thumbnail when hovered on.

It's not noticeable on most thumbnails since it blends in, but it's more obvious on thumbnails with more even coloring in that area.

![image](https://user-images.githubusercontent.com/13057505/79113463-f59f4b80-7d4e-11ea-8faa-fda738dbc353.png)

**Comment by stefanciorici** [comment]
Oh, sorry. Should be fixed now.
