### ISSUE TITLE
Change "default_camera_position_direction" to be relative to asset location

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#79]
The camera location should be relative to the x,y,z coordinates of the local asset

**Comment by 3DGISKing** [comment]
done please check.

https://github.com/outsider787/gw3_construkted/wiki/Construkted-Meta-Data-Definition

**Comment by outsider787** [comment]
Just recording heading, pitch and range is not enough. This does not allow me to record the full location of the camera.

We need to record a location for the camera (as well as the heading, pitch and roll of the camera)
That location should be a x,y,z coordinate relative to the asset.

**Comment by 3DGISKing** [comment]
Let 's say asset 's boundingbox 's center position is (10, 10, 10) and current camera position is (30, 30, 30)
then "x,y,z coordinate relative to the asset" means (30 -10, 30 -10, 30 -10)?
