### ISSUE TITLE
asset processing progress indicator

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#8]
On the "MY ASSETS" page, ( https://gw3.construkted.com/profile/?active_tab=posts ) change the progress indicator to only display percentage. I don't want the users to know all the steps that are being taken.
In the code, keep a reference of the status, but what is displayed to the user should just be a percentage.
Use the following guideline to determine progress indicator:

0% | Unknown
5% | Creating Asset
5-20%   | Uploading
20-70% | Tiling
70% | Downloading tileset
80% | Packaging
90% | Deleting tileset
95% | Finished

The states "Uploading" and "Tiling" report back a percentage. Adjust the reported percentage to reflect the range listed above.

**Comment by 3DGISKing** [comment]
fixed
