### ISSUE TITLE
Asset page layout change

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#83]
I was sketching out an idea for a slightly different layout for the asset display page.
I wanted to display the asset name somehow into the displayed page, without having to scroll down to see it.

So this is what I came up with. **Let me know your thoughts.**

When an asset page is loaded, the bottom of the page should be the red line. This means that the tile and a few icons are always visible. 
- Remove the "Details " button
- Move the "Edit" and "Report Video" buttons
- "Report Video" button should be renamed to "Report Asset"
- Move the Share, Likes buttons to the top, in line with title.
- Move the "Embed" and "Download" buttons to the top, in line with title.
- Move "Asset Metadata" area down.

![image](https://user-images.githubusercontent.com/13057505/79133920-d61e1800-7d7a-11ea-987d-fdf2b0484ce8.png)

I got the idea from the way YouTube arranges their video pages:

![image](https://user-images.githubusercontent.com/13057505/79133850-b5ee5900-7d7a-11ea-8c4f-887a3a5654d7.png)

**Comment by stefanciorici** [comment]
We already changed these to the design provided. Any additional changes required here?
