### ISSUE TITLE
EMBED code does not work

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#85]
The EMBED code does not display the asset. It throws a bunch of JS errors.

<iframe src="https://gw3.construkted.com/embed/l4sav2ekd8" width="680" height="480"></iframe>

![image](https://user-images.githubusercontent.com/13057505/79751540-c2c1fe00-82e0-11ea-8ab7-070ef245d2ea.png)

**Comment by 3DGISKing** [comment]
I see. Let me fix

**Comment by 3DGISKing** [comment]
Fixed. Please check.
