### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#90]
What does "Validate Video" do? 
And once clicked, what does "Reviewed by admin" mean?

![image](https://user-images.githubusercontent.com/13057505/80214183-61639d00-8608-11ea-9c55-58c9c5222f0e.png)

![image](https://user-images.githubusercontent.com/13057505/80214295-953ec280-8608-11ea-9a48-cf37f85af262.png)

**Comment by stefanciorici** [comment]
Those appear to the admj if somebody clicked the Report button. If you click to review it users cannot report it any more.

**Comment by outsider787** [comment]
Understood.
Thanks!
