### ISSUE TITLE
PRODUCTION- Upload error

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#92]
After the uploading of a file to the production server, I get an error.
- This error does not happen with smaller files.
- This error does not happen on **gw3 server**. 

Use this file to test
https://s3.us-east-2.wasabisys.com/construkted-uploads/admin/9cmp-7h71%20Kuda%20Miskii%20Èxported%20Mesh.zip

![image](https://user-images.githubusercontent.com/13057505/80615196-5e541c80-8a0d-11ea-857a-09825f0cdf31.png)

**Comment by outsider787** [comment]
Fixed
Needed to increase the max file size for php in CPanel

![image](https://user-images.githubusercontent.com/13057505/80618873-f2c07e00-8a11-11ea-8ff0-3c7164e541f6.png)

**Comment by 3DGISKing** [comment]
I see.
