### ISSUE TITLE
FPV mode bug

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#94]
When the asset altitude is negative, FPV mode doesn't work.

Test with this asset
https://construkted.com/asset/ajxdrwtn5j6/

![image](https://user-images.githubusercontent.com/13057505/80819611-44e4d900-8ba3-11ea-83e2-2b77a0290014.png)

**Comment by outsider787** [comment]
You can test with this asset on gw3 site.
It has the same issue.
https://gw3.construkted.com/asset/lrxjfjysn5/

Model is set to a negative altitude because that's the terrain altitude.
![image](https://user-images.githubusercontent.com/13057505/80924608-e2810980-8d57-11ea-8358-b340ca38ba65.png)

**Comment by 3DGISKing** [comment]
I don't think so

**Comment by 3DGISKing** [comment]
I misunderstood.  
Cesium createWorldTerrain provider gives negative height value on some places.
fixed on gw3.
