### ISSUE TITLE
Control API URL

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#97]
Create another tab in the Settings>Construkted page. Name of the tab is "API Settings"
![image](https://user-images.githubusercontent.com/13057505/80830719-7798cc80-8bb7-11ea-93e6-9f553acad16a.png)

In that tab, create a text field with the label "API URL", 
This text field controls the API URL for the entire website, and should be saved in the WP database.
There are 4 locations in the theme that use the API URL. Change all locations to read the URL from the data on this tab.
![image](https://user-images.githubusercontent.com/13057505/80830668-5f28b200-8bb7-11ea-8323-2579b7c47d3e.png)

**Comment by 3DGISKing** [comment]
I see

**Comment by 3DGISKing** [comment]
done. please check

**Comment by outsider787** [comment]
please make the same change to:
- Production website
- devel01 website

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
please check.
