### ISSUE TITLE
Delete file after moving to S3

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#99]
After the uploaded file is copied to Wasabi S3, delete the local copy on the web server right away.

**Comment by 3DGISKing** [comment]
Currently the uploaded file is deleted from WordPress server after the construkted asset is published.
Do you want to change the moment for deleting?

**Comment by outsider787** [comment]
Yes.
We should delete the zip file right after it is sent to Wasabi.
Do not wait until asset is published.

**Comment by 3DGISKing** [comment]
Ok. I see

**Comment by 3DGISKing** [comment]
done on tile-gw3/gw3.construkted.com.

**Comment by 3DGISKing** [comment]
please test and let me know. after I will update the production site and devel01.

**Comment by outsider787** [comment]
I tested GW3 site.
It works.

Please make changes to production and devel01 sites

**Comment by 3DGISKing** [comment]
Yes

**Comment by 3DGISKing** [comment]
production site updated with this issue.

**Comment by 3DGISKing** [comment]
til02/devel01 updated with this issue.
